debug:
  enabled: false
  console: true # Логировать в консоль?
  prefix: "&e[Откладка &8|&r %s&e]"
  info: "ИНФО"
  warn: "&eПРЕД"
  error: "&cОШИБКА"

items:
  loadBlockedItems: no
  registerTestItems: yes

blacklistedItems: []
