debug:
  enabled: no

  # Log to console?
  console: yes

  #TailsLib will stop reporting errors that may break the server or plugin errors.
  #By default, TailsLib will send error messages to the player even if debug.enabled is turned off.
  supressErrors: no

  # Prefix for debug.
  prefix: "&r[%s&r]"
  info: "ИНФО"
  warn: "&eПРЕД"
  error: "&cОШИБКА"

items:
  loadBlockedItems: no

tests:
  registerTests: yes

effects:
  sendMessages: yes

waitBeforeLoadBlocks: 2

autosaveEnabled: yes

blacklistedItems: []
