debug:
  enabled: false
  console: true # Логировать в консоль?
  prefix: "&r[%s&r]"
  info: "ИНФО"
  warn: "&eПРЕД"
  error: "&cОШИБКА"

items:
  loadBlockedItems: no
  registerTestItems: yes

# Плагин не начнёт загружать определённые вещи пока остальные модули не будут запущены.
# Нужно вводить название плагина указанное в plugin.yml
modules: []

blacklistedItems: []
